<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2EuMFex\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2EuMFex/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2EuMFex.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2EuMFex\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2EuMFex\App_KernelDevDebugContainer([
    'container.build_hash' => '2EuMFex',
    'container.build_id' => '4e4a60b5',
    'container.build_time' => 1636990302,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2EuMFex');
