index:
  path: /
  controller: App\Controller\AccueilController::index

home:
  path: /home
  controller: App\Controller\AccueilController::home

#enseigne
enseigneAjouter:
  path: /enseigne/ajouter
  controller: App\Controller\EnseigneController::ajouterEnseigne

enseigneConsulter:
  path: /enseigne/consulter/{id}
  controller: App\Controller\EnseigneController::consulterEnseigne

enseigneLister:
  path: /enseigne/lister
  controller: App\Controller\EnseigneController::listerEnseigne

enseigneModifier:
  path: /enseigne/modifier/{id}
  controller: App\Controller\EnseigneController::modifierEnseigne

enseigneSupprimer:
  path: /enseigne/supprimer/{id}
  controller: App\Controller\EnseigneController::supprimerEnseigne

#magasin
magasinAjouter:
  path: /magasin/ajouter
  controller: App\Controller\MagasinController::ajouterMagasin

magasinConsulter:
  path: /magasin/consulter/{id}
  controller: App\Controller\MagasinController::consulterMagasin

magasinLister:
  path: /magasin/lister
  controller: App\Controller\MagasinController::listerMagasin

magasinSupprimer:
  path: /magasin/supprimer/{id}
  controller: App\Controller\MagasinController::supprimerMagasin
  

#typeEnseigne
typeEnseigneAjouter:
  path: /type_enseigne/ajouter
  controller: App\Controller\TypeEnseigneController::ajouterTypeEnseigne

typeEnseigneConsulter:
  path: /type_enseigne/consulter/{id}
  controller: App\Controller\TypeEnseigneController::consulterTypeEnseigne

typeEnseigneLister:
  path: /type_enseigne/lister
  controller: App\Controller\TypeEnseigneController::listerTypeEnseigne

#responsable
responsableAjouter:
  path: /responsable/ajouter
  controller: App\Controller\ResponsableController::ajouterResponsable

responsableConsulter:
  path: /responsable/consulter/{id}
  controller: App\Controller\ResponsableController::consulterResponsable

responsableLister:
  path: /responsable/lister
  controller: App\Controller\ResponsableController::listerResponsable

reponsableSupprimer:
  path: /responsable/supprimer/{id}
  controller: App\Controller\ResponsableController::supprimerResponsable

  #interlocuteur
interlocuteurAjouter:
  path: /interlocuteur/ajouter
  controller: App\Controller\InterlocuteurController::ajouterInterlocuteur

interlocuteurConsulter:
  path: /interlocuteur/consulter/{id}
  controller: App\Controller\InterlocuteurController::consulterInterlocuteur

interlocuteurLister:
  path: /interlocuteur/lister
  controller: App\Controller\InterlocuteurController::listerinterlocuteur

interlocuteurModifier:
  path: /interlocuteur/modifier/{id}
  controller: App\Controller\InterlocuteurController::modifierInterlocuteur

interlocuteurSupprimer:
  path: /interlocuteur/supprimer/{id}
  controller: App\Controller\InterlocuteurController::supprimerInterlocuteur
